import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
import './styles.css';
import './v3.css';
import './v4.css';
import './v5.css';
import './collection-room.css';
import {questPreview} from './lib/useToyQuest';
import {CollectionPreview} from './components/CollectionPreview';
createRoot(document.getElementById('root')!).render(<React.StrictMode>{questPreview?<CollectionPreview/>:<App/>}</React.StrictMode>);
